### PR TITLE
Add domain open console in driver support

### PR DESCRIPTION
**Pull request by zarcen**
Add .domainOpenConsole in CH function tables to support `virsh console <domain>`
The guest VM has to configure serial port device beforehand.

### CODE REVIEW

**Comment by sameo** [comment]
Fixes #19

**Comment by bryteise** [comment]
LGTM

**Comment by eeldy** [comment]
Excuse me，how could I configure serial port device for the CH guest VM beforehand to make virsh console works?
Maybe by virsh create a.xml or sth else? Thanks a lot.

**Comment by bryteise** [comment]
@eeldy Currently there is some work needed in Cloud Hypervisor in order to support virsh console. It is something I'm currently working on.

**Pull request merged**
