### PR TITLE
Update CH's API scheme

### PR DESCRIPTION
**Pull request by pupacha**
Addresses https://github.com/cloud-hypervisor/libvirt/issues/102 

Starting from v28.0, there will be change in CH's API scheme. Top level kernel, cmdline, initramfs are moved under payload. More information in the following release notes.
https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v26.0

Signed-off-by: Purna Pavan Chandra <paekkaladevi@microsoft.com>

### CODE REVIEW

**Review by sboeuf — APPROVED** [review]

**Review by jinankjain — APPROVED** [review]

**Review by weltling — APPROVED** [review]
Thanks for the quick fix.

The related issue #102 should be mentioned in the description.

Thanks

**Review by praveen-pk — APPROVED** [review]

**Comment by weltling** [comment]
The CI should probably be moving towards github actions, but as a quick solution perhaps could change the label to `jammy` for now? See https://github.com/cloud-hypervisor/libvirt/blob/ch/Jenkinsfile#L25.

Thanks

**Comment by praveen-pk** [comment]
Seems like the CI is not being run as there are no available nodes. As this doesn't make any functional changes, I went ahead and merged it.

**Comment by pupacha** [comment]
> Seems like the CI is not being run as there are no available nodes. As this doesn't make any functional changes, I went ahead and merged it.

Thanks @praveen-pk

**Comment by praveen-pk** [comment]
I jumped the gun on this merge. I didn't review the second commit in this PR.
The second commit didn't resolve the issue with identifying correct CI nodes to run tests on. A follow up commit will be pushed to revert the second commit in this PR.

**Comment by rbradford** [comment]
How do you plan to reconcile the difference with upstream and the version you have here?

**Comment by praveen-pk** [comment]
@rbradford do you mean libvirt version?

We pushed some of the features we developed in this fork to upstream. Unfortunately, the version in upstream is not stable either. Some resources should be committed to fix the upstream version and push rest of the features in this fork to upstream. I do not have plan for it at the moment.

**Pull request merged**
