### PR TITLE
Initial pci pass through support for Cloud-Hypervisor

### PR DESCRIPTION
**Pull request by bryteise**
There is some issue with booting still that I haven't quite figured
out. As a temporary workaround, if you run vm.shutdown and vm.boot
with curl on the socket created by libvirt in that order it will bring
the vm up but libvirt is stuck in an bad state.

Might be a bug with the ch socket handling code. Will need more
investigation.

### CODE REVIEW

**Comment by bryteise** [comment]
@vineethrp This is a little premature unfortunately but it is relatively the initial implementation I'm going for since it fits the the current setup. Sadly it still has a critical bug left over that I'll poke at tomorrow a bit more.

**Comment by bryteise** [comment]
@vineethrp This version is working for me now without issue. Let me know if you get time to test it!

**Comment by vineethrp** [comment]
Thanks @bryteise. I will give it a try later this week. Will keep you posted..

**Comment by bryteise** [comment]
Resolves #16 and #15.

**Comment by praveen-pk** [comment]
@bryteise  after running through some issues I verified PCI pass through feature.

I can now see a PCI device on host:
```
04:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983
```
from inside guest VM:
```
testuser@chtestvm:~$ lspci | grep NVM
00:06.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983
```
What I noticed here is that I had to manually create a vfio device in order for PCI passthrough to work. Is that expected?

**Comment by praveen-pk** [comment]
As verified from above testing, this version doesn't yet support Automatic Host Dev Management. A follow up bug will be tracked for host device management.

**Review by praveen-pk — APPROVED** [review]

**Review by praveen-pk — APPROVED** [review]

**Pull request merged**
