### PR TITLE
Implement domainInterfaceAddresses and nodeGetMemoryStats for CH driver

### PR DESCRIPTION
**Pull request by anirudhrb**

### CODE REVIEW

**Comment by praveen-pk** [comment]
Please address the build failure reported above. Secondly, please post relevant excerpt of guest domain XML used in your testing for this PR

**Comment by vyadavmsft** [comment]
@praveen-pk for review.

**Comment by anirudhrb** [comment]
> Please address the build failure reported above. Secondly, please post relevant excerpt of guest domain XML used in your testing for this PR

I have added the version but the `ch_integration_tests.sh` seems to be broken. It is trying to fetch master branch of cloud-hypervisor which doesn't exist (renamed to main I think).

Here's the domain network interface config I tested with
```xml
<interface type='network'>
  <source network='default'/>
  <driver queues='2' iommu='on'/>
  <model type='virtio'/>
</interface>
```

Here `default` network is same as the one defined in `/etc/libvirt/qemu/networks/default.xml`.

**Comment by rbradford** [comment]
You could add a commit to your PR to fix `ch_integration_tests/build_ch.sh`

**Pull request merged**
