### PR TITLE
ch_integration_tests: Add basic VM boot test

### PR DESCRIPTION
**Pull request by rbradford**
Add a test that tries to create a VM.

The tests don't yet wait for the guest to come up on the network as
there are gaps in the libvirt CH driver VM network configuration.

Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Comment by bryteise** [comment]
@rbradford Could you take a look at https://github.com/bryteise/libvirt/commit/0e22b65b817108ac38c450baaf60e7186a4613c2 and see if that works for you to set up a network nicely. I didn't get time to hook up the ssh check though sorry. I ended up pounding my head against the wall because libvirt saved some network config from a random debug run in /etc for reasons beyond me and I couldn't figure out why I was getting devices I no longer declared X(.

**Comment by rbradford** [comment]
@bryteise I rebased your change and I get the following error:

```
libvirtd stderr

2021-03-24 14:11:11.669+0000: 10930: info : libvirt version: 6.7.0
2021-03-24 14:11:11.669+0000: 10930: info : hostname: rbradford-test
2021-03-24 14:11:11.669+0000: 10930: error : networkCheckRouteCollision:296 : internal error: Network is already in use by interface virbr0
2021-03-24 14:11:18.310+0000: 10917: error : virNetworkCreateXML:420 : this function is not supported by the connection driver: virNetworkCreateXML
2021-03-24 14:11:23.351+0000: 10916: error : virNetworkLookupByName:305 : this function is not supported by the connection driver: virNetworkLookupByName

thread 'tests::test_create_vm' panicked at 'assertion failed: r.is_ok()', tests/integration.rs:300:9
```

Are there some libvirt changes themselves missing?

**Comment by rbradford** [comment]
> 2021-03-24 14:11:11.669+0000: 10930: error : networkCheckRouteCollision:296 : internal error: Network is already in use by interface virbr0

Removing `/etc/libvirt` gets rid of this particular error but the others remain.

**Comment by bryteise** [comment]
Closing this, I think we are seeing a way forward with one of the changes this is based on.

**Pull request closed without merging**
