### PR TITLE
Update focal image name for tests

### PR DESCRIPTION
**Pull request by vyadavmsft**

### CODE REVIEW

**Comment by bryteise** [comment]
@vyadavmsft It looks like there is an issue with the Jenkinsfile. I think using https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/Jenkinsfile#L194 is what we should be doing instead of https://github.com/cloud-hypervisor/libvirt/blob/ch/Jenkinsfile#L34.

**Comment by bryteise** [comment]
@vyadavmsft you also need to swap out https://github.com/cloud-hypervisor/libvirt/pull/97/commits/048014b6acb003632c0d7943b8e6f42b6ddbc8d2#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8R36 for https://github.com/cloud-hypervisor/cloud-hypervisor/blob/43f1a32859cd75418c2505b66b44aaa3c0061891/Jenkinsfile#L196.

**Comment by bryteise** [comment]
@sboeuf could you take a look at this and tell me what's wrong? Based on https://github.com/cloud-hypervisor/cloud-hypervisor/commit/c93b7037b490e88d3044f605544b77b25b4d70fa I was expecting the latest change in the PR to work.

**Comment by sboeuf** [comment]
@bryteise
>could you take a look at this and tell me what's wrong? Based on cloud-hypervisor/cloud-hypervisor@c93b703 I was expecting the latest change in the PR to work.

The PR is fine and I expect it to work as well. The problem comes from the fact that only a certain set of people can submit changes to the `Jenkinsfile`. I think if you submit the PR yourself, things should work.

@rbradford where can I find the list of approved people to modify the Jenkinsfile?

**Comment by rbradford** [comment]
> @rbradford where can I find the list of approved people to modify the Jenkinsfile?

Anyone with write access to the repository can do it (which will be managed by the appropriate team.)

**Comment by bryteise** [comment]
Closed in favor of #98

**Pull request closed without merging**
